version: '3'
services:
  database:
    image: "postgres"
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql2/data/
    ports:
      - 5432:5432 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  database-data: # named volumes can be managed easier using docker-compose
